fix: force environment in workflow visualization console command
Error: The workflow visualization didn't work on our client-acceptance environment
Caused by: Wrong Pimcore environment was used in the command used to build the visualization
Resolved by: Explicitly passing the enviroment in the console command call